### ISSUE TITLE
JWT token headers could have additional fields also

### ISSUE THREAD

**Issue by kvijay1918** [Comcast/cjwt#54]
Why do you expect the JWT token header should only have alg and type? It can also contain additional fields right?

```
    cJSON_DeleteItemFromObjectCaseSensitive(json, "alg");
    cJSON_DeleteItemFromObjectCaseSensitive(json, "typ");

     if (json->next || json->prev || json->child) {
        return CJWTE_HEADER_UNSUPPORTED_UNKNOWN;
    }
```

This statement piece should be removed I guess. Please do review this piece and update it.

Sample header :

{
  "alg": "PS384",
  "url": "some-url",
  "kid": "1234",
  "typ": "JWT"
}

This is failing in your code. But it should not.

**Comment by schmidtw** [comment]
JWS headers aren't generally supported as they require fetching the public key, etc.  Out of the list allowed by [JWS](https://datatracker.ietf.org/doc/html/rfc7515) Section 4, only `jwk` and `kid` appear safe to allow.  All others will be disallowed because the library can't honor them.  If they are honored, they can be added.

Non-registered headers aren't supported in this version, but if you want them, please send a PR.  Any reserved values that aren't honored will need to render an error if present.  This helps protect against attacks.

**Comment by kvijay1918** [comment]
Support added and raised PR. Please do review the changes.

Code : https://github.com/kvijay1918/cjwt/tree/task/add-new-fields-to-header
PR : https://github.com/xmidt-org/cjwt/pull/57

**Comment by schmidtw** [comment]
Thank you for the PR.  I reviewed `jku` header and confirmed I do not want to add it.  Specifically it allows an attacker to replace the signing service url with their own.  This is an example of how that happens: https://blog.pentesteracademy.com/hacking-jwt-tokens-jku-claim-misuse-2e732109ac1c

But other private values are now supported in #59 .
